// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoa6j_UlXxsxYIiTSxgrb3HVlvMH5ctAE',
    appId: '1:549271994029:web:71e361b465ca43fed29024',
    messagingSenderId: '549271994029',
    projectId: 'manage-payment-app-backend',
    authDomain: 'manage-payment-app-backend.firebaseapp.com',
    storageBucket: 'manage-payment-app-backend.firebasestorage.app',
    measurementId: 'G-276MHN711Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdY8ld5gyRECnnwX6wYlpoZl8y4AUl4xU',
    appId: '1:549271994029:android:f21718fb0f2c0ab0d29024',
    messagingSenderId: '549271994029',
    projectId: 'manage-payment-app-backend',
    storageBucket: 'manage-payment-app-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYB8Wtys9wyj0hup07lS-6s3E7tT6t4gk',
    appId: '1:549271994029:ios:e9afcf7012091820d29024',
    messagingSenderId: '549271994029',
    projectId: 'manage-payment-app-backend',
    storageBucket: 'manage-payment-app-backend.firebasestorage.app',
    iosBundleId: 'com.example.managePaymentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYB8Wtys9wyj0hup07lS-6s3E7tT6t4gk',
    appId: '1:549271994029:ios:e9afcf7012091820d29024',
    messagingSenderId: '549271994029',
    projectId: 'manage-payment-app-backend',
    storageBucket: 'manage-payment-app-backend.firebasestorage.app',
    iosBundleId: 'com.example.managePaymentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoa6j_UlXxsxYIiTSxgrb3HVlvMH5ctAE',
    appId: '1:549271994029:web:d6955a1c1598d319d29024',
    messagingSenderId: '549271994029',
    projectId: 'manage-payment-app-backend',
    authDomain: 'manage-payment-app-backend.firebaseapp.com',
    storageBucket: 'manage-payment-app-backend.firebasestorage.app',
    measurementId: 'G-8G4BVEFEJJ',
  );
}
